name: Future Net Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # يتيح لك تشغيل البوت يدوياً أيضاً

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install pyTelegramBotAPI google-genai

      - name: Run Future Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python bot.py
